#!/bin/bash

PATH=${PATH}:/home/syllogismrxs/git-repos/linux-setup/scripts

pushd /home/syllogismrxs >& /dev/null

# Execute the emacs script to generate the ics file
emacs-org-export

# Move the ics file to the web server
mv /home/syllogismrxs/org.ics /var/www/calendars/emacs.ics

popd >& /dev/null
